### ISSUE TITLE
Problem with code compatibility with Python 3.9

### ISSUE THREAD

**Issue by samwathegreat** [0x9900/igate_telem#3]
Attempting to run /usr/local/bin/igate_telem -d on python 3.9 results in an error:  "TypeError: a bytes-like object is required, not 'str'
"

Unfortunately, I'm not familiar enough with Python to be able to fix the error.  It seems this has to do with changes from python 2 to python 3.

Any help with getting this working would be appreciated.  I want to be able to run this on my Pi4.

**Comment by samwathegreat** [comment]
Solution found - pull request sent.

**Comment by 0x9900** [comment]
I am running it on a Python3.8 on my raspberry. Unfortunately, I don’t have right now a RPI running with python3.9. 
If you could give me the line number where you see this error it will help me, because with python3.8 everything is fine.

-fred-


-- 
Fred C.
***@***.***
https://0x9900.com/ <https://0x9900.com/>
https://www.qrz.com/db/W6BSD <https://www.qrz.com/db/W6BSD>

**Comment by samwathegreat** [comment]
Hi Fred,

This issue was created before I found the solution and made the pull
request, so it's resolved now.  If it helps, the error was on this line:
      self.st_data = pickle.loads(sfd.read())


There is, however, a new issue that I can't
figure out regarding rx and tx packets showing fractions of a whole number.
